#!/bin/bash -eux
#SBATCH --job-name=CITs_benchmarking
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=marco.simnacher@guest.hpi.de
#SBATCH --partition=gpu,cpu,gpua100,gpupro # -p
#SBATCH --cpus-per-task=40 # -c
#SBATCH --mem=256gb
#SBATCH --gpus=0
#SBATCH --time=06:00:00 
#SBATCH --output=logs/WALD_%j.log # %j is job id

set +u
eval "$(conda shell.bash hook)"
conda activate /dhc/home/marco.simnacher/conda3/envs/install-dncit

# args = [dependence fct_relation eps_sigmaX eps_sigmaY eps_sigmaZ embedding_orig embedding_obs confounder response cit cit params]
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z1 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z2 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z4 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z6 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z10 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 linear WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 squared WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 realistic WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 1 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 2 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 3 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 4 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer fastsurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 3 1 0 fastsurfer noisy ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer freesurfer ukb_z15 breakpoint3 WALD
Rscript raw_code/sim_ukb_brainmri.R /No_CI/ 5 0 1 0 fastsurfer condVAE ukb_z15 breakpoint3 WALD
set -u
